### ISSUE TITLE
Add Document

### ISSUE THREAD

**Issue by moba1** [alex-lairan/monads#49]
I would like to create documentation by using [GitBook](https://www.gitbook.com/).

**Comment by alex-lairan** [comment]
I would like too.

I created this : https://lairana.gitbook.io/monads/

How can I invite you on the gitbook ?

**Comment by alex-lairan** [comment]
I created an organisation.

Now it's this name : https://monads.gitbook.io/docs/

**Comment by moba1** [comment]
Can you make invaited link?

**Comment by moba1** [comment]
ref. https://docs.gitbook.com/organization-management/member-management

**Comment by moba1** [comment]
Or, use [gitbook-cli](https://github.com/GitbookIO/gitbook-cli) and GitHub Pages.

**Comment by moba1** [comment]
However, this method has disadvantage that another repository has to be created.

**Comment by alex-lairan** [comment]
Yes, I can create a link.

Do you use gitter ?
Or anything else where I can send you the link.

**Comment by moba1** [comment]
I had gitter account
